name: Deploy IncidentApp

on:
  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    
    environment: production
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pack-solution.yml
          name: packed-solution
      - uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: ${{ vars.ENVIRONMENT_URL }}
          user-name: ${{ secrets.USERNAME }}
          password-secret: ${{ secrets.PASSWORD }}
          solution-file: IncidentApp_managed.zip